'use strict'

import MONGO_CONFIG from './MONGO_CONFIG'
import SERVER_CONFIG from './SERVER_CONFIG'
import EXPS_CONFIG from './EXPS_CONFIG'
import RAZORPAYX_CONFIG from './RAZORPAYX_CONFIG'

export {
  MONGO_CONFIG,
  SERVER_CONFIG,
  EXPS_CONFIG,
  RAZORPAYX_CONFIG
}
